const contractEnum = {
  TRANSACTION_CONTRACT_INIT: "TRANSACTION_CONTRACT_INIT",
  TRANSACTIONS: "TRANSACTIONS",
  TRANSACTION_COUNT: "TRANSACTION_COUNT",
  TOKEN_CONTRACT_INIT: "TOKEN_CONTRACT_INIT",
  TOKEN_PRICE: "TOKEN_PRICE",
  SALE_CONTRACT_INIT: "SALE_CONTRACT_INIT",
  LOTTERY_INIT: "LOTTERY_INIT",
  LOTTERY_POOL_CONTRACT_INIT: "LOTTERY_POOL_CONTRACT_INIT",
  LOTTERY_TIME_REMAINING: "LOTTERY_TIME_REMAINING",
  LOTTERY_MANAGER: "LOTTERY_MANAGER",
  LOTTERY_ENTRY_FEE: "LOTTERY_ENTRY_FEE",
  LOTTERY_PLAYERS: "LOTTERY_PLAYERS",
  LOTTERY_WINNER: "LOTTERY_WINNER",
  LOTTERY_PRICE: "LOTTERY_PRICE",
  LOTTERIES_DETAILS: "LOTTERIES_DETAILS"
};

const web3Enum = {
  PROVIDER: "PROVIDER",
};

const tokenEnum = {
  PRICE: "PRICE",
  BALANCE: "BALANCE",
  SOLD: "SOLD",
};

const userEnum = {
  BALANCE: "BALANCE",
  CURR_ACCOUNT: "CURR_ACCOUNT",
};

export { contractEnum, web3Enum, tokenEnum, userEnum };
